import img1 from "../../assets/images/Image.png";
import img2 from "../../assets/images/Image (1).png";
import img3 from "../../assets/images/Image (2).png";
import img4 from "../../assets/images/Image (3).png";
import troll1 from "../../assets/images/Image (4).png";
import troll2 from "../../assets/images/Image (5).png";
import troll3 from "../../assets/images/Image (6).png";
import troll4 from "../../assets/images/Image (7).png";
import troll5 from "../../assets/images/Image (8).png";
import sIcon from "../../assets/images/s.png";
import vIcon from "../../assets/images/v.png";

export const flufWorldState = {
  flufData: [
    {
      id: 1,
      image: img3,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 2,
      image: img1,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 3,
      image: img2,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 4,
      image: img4,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 5,
      image: img1,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 6,
      image: img2,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 7,
      image: img3,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 8,
      image: img4,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 9,
      image: img1,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 10,
      image: img3,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 11,
      image: img4,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 12,
      image: img2,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 13,
      image: img3,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 14,
      image: img4,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 15,
      image: img1,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
    {
      id: 16,
      image: img2,
      number: "#738",
      count: 0.5,
      world: "Fluf World",
      offer: 0.35,
      owner: "ERC-721",
    },
  ],
  rarityChartData: [
    {
      id: 1,
      number: "#1",
      score: "Rarity score: 3120",
      image: troll1,
      icon: sIcon,
      name: "Troll God #23",
      v: "v1",
      
    },
    {
      id: 2,
      number: "#2",
      score: "Rarity score: 3120",
      image: troll2,
      icon: sIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 3,
      number: "#3",
      score: "Rarity score: 3120",
      image: troll3,
      icon: vIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 4,
      number: "#4",
      score: "Rarity score: 3120",
      image: troll3,
      icon: vIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 5,
      number: "#5",
      score: "Rarity score: 3120",
      image: troll4,
      icon: sIcon,
      name: "Troll God #23",
      v: "v2",
    },
    {
      id: 6,
      number: "#6",
      score: "Rarity score: 3120",
      image: troll1,
      icon: vIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 7,
      number: "#7",
      score: "Rarity score: 3120",
      image: troll5,
      icon: sIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 8,
      number: "#8",
      score: "Rarity score: 3120",
      image: troll2,
      icon: sIcon,
      name: "Troll God #23",
      v: "v2",
    },
    {
      id: 9,
      number: "#9",
      score: "Rarity score: 3120",
      image: troll3,
      icon: vIcon,
      name: "Troll God #23",
      v: "v2",
    },
    {
      id: 10,
      number: "#10",
      score: "Rarity score: 3120",
      image: troll1,
      icon: sIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 11,
      number: "#11",
      score: "Rarity score: 3120",
      image: troll2,
      icon: sIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 12,
      number: "#12",
      score: "Rarity score: 3120",
      image: troll3,
      icon: vIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 13,
      number: "#13",
      score: "Rarity score: 3120",
      image: troll3,
      icon: vIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 14,
      number: "#14",
      score: "Rarity score: 3120",
      image: troll4,
      icon: sIcon,
      name: "Troll God #23",
      v: "v2",
    },
    {
      id: 15,
      number: "#15",
      score: "Rarity score: 3120",
      image: troll1,
      icon: vIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 16,
      number: "#16",
      score: "Rarity score: 3120",
      image: troll5,
      icon: sIcon,
      name: "Troll God #23",
      v: "v1",
    },
    {
      id: 17,
      number: "#17",
      score: "Rarity score: 3120",
      image: troll2,
      icon: sIcon,
      name: "Troll God #23",
      v: "v2",
    },
    {
      id: 18,
      number: "#18",
      score: "Rarity score: 3120",
      image: troll3,
      icon: vIcon,
      name: "Troll God #23",
      v: "v2",
    },
  ],
};
